[project]
name = "py-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "alembic>=1.18.3",
    "psycopg[binary]>=3.3.2",
    "sqlalchemy[asyncio]>=2.0.46",
]
