[project]
name = "science"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.4",
    "fastembed>=0.7.4",
    "marimo>=0.19.7",
    "polars>=1.37.1",
    "scikit-learn>=1.8.0",
]
